#!/usr/bin/env bash
# sync-engine.sh — YourAI core/custom 同期エンジン v2.0.0
# core/CLAUDE_BASE.md + custom/CLAUDE_LOCAL.md → CLAUDE.md を生成
# core/skills/ + custom/skills/ → .claude/skills/<name>/SKILL.md にマージ（v2: skills形式）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CORE_BASE="$SCRIPT_DIR/core/CLAUDE_BASE.md"
CUSTOM_LOCAL="$SCRIPT_DIR/custom/CLAUDE_LOCAL.md"
OUTPUT_CLAUDE="$SCRIPT_DIR/CLAUDE.md"
CORE_SKILLS="$SCRIPT_DIR/core/skills"
CUSTOM_SKILLS="$SCRIPT_DIR/custom/skills"
TARGET_SKILLS="$SCRIPT_DIR/.claude/skills"
VERSION_FILE="$SCRIPT_DIR/core/version.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

DRY_RUN=false
FORCE=false
DIFF_MODE=false

usage() {
    echo "Usage: sync-engine.sh [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --dry-run    Show what would change without writing"
    echo "  --diff       Show diff between current and new CLAUDE.md"
    echo "  --force      Overwrite even if CLAUDE.md has local edits"
    echo "  -h, --help   Show this help"
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run) DRY_RUN=true; shift ;;
        --diff) DIFF_MODE=true; shift ;;
        --force) FORCE=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1"; usage; exit 1 ;;
    esac
done

# Validation
if [[ ! -f "$CORE_BASE" ]]; then
    echo -e "${RED}[ERROR] core/CLAUDE_BASE.md not found${NC}"
    exit 1
fi
if [[ ! -f "$CUSTOM_LOCAL" ]]; then
    echo -e "${RED}[ERROR] custom/CLAUDE_LOCAL.md not found${NC}"
    exit 1
fi

echo -e "${GREEN}[sync-engine]${NC} Starting sync..."
echo "  Core:   $CORE_BASE"
echo "  Custom: $CUSTOM_LOCAL"

# --- Step 1: Merge CLAUDE.md ---
HEADER="<!-- AUTO-GENERATED by sync-engine.sh — DO NOT EDIT DIRECTLY -->
<!-- Edit core/CLAUDE_BASE.md or custom/CLAUDE_LOCAL.md instead -->
<!-- Last sync: $(date -u +"%Y-%m-%dT%H:%M:%SZ") | Core v$(python3 -c "import json; print(json.load(open('$VERSION_FILE'))['core_version'])" 2>/dev/null || echo '1.0.0') -->"

MERGED="${HEADER}

$(cat "$CORE_BASE")

---

# インスタンス固有設定

$(cat "$CUSTOM_LOCAL")
"

if $DIFF_MODE; then
    if [[ -f "$OUTPUT_CLAUDE" ]]; then
        echo -e "${YELLOW}[diff]${NC} Current vs Generated CLAUDE.md:"
        diff <(cat "$OUTPUT_CLAUDE") <(echo "$MERGED") || true
    else
        echo -e "${YELLOW}[diff]${NC} CLAUDE.md does not exist yet (will be created)"
    fi
    exit 0
fi

if $DRY_RUN; then
    echo -e "${YELLOW}[dry-run]${NC} Would generate CLAUDE.md ($(echo "$MERGED" | wc -l | tr -d ' ') lines)"
else
    echo "$MERGED" > "$OUTPUT_CLAUDE"
    echo -e "${GREEN}[OK]${NC} CLAUDE.md generated ($(wc -l < "$OUTPUT_CLAUDE" | tr -d ' ') lines)"
fi

# --- Step 2: Merge skills → .claude/skills/<name>/SKILL.md ---

# Helper: Extract first heading line as description fallback
extract_description() {
    local file="$1"
    # Try to get the first # heading text
    grep -m1 '^# ' "$file" | sed 's/^# //' || echo ""
}

# Helper: Convert a flat .md skill file to SKILL.md format with frontmatter
convert_skill() {
    local src="$1"
    local dest_dir="$2"
    local basename="$(basename "$src" .md)"

    local dest="$dest_dir/$basename/SKILL.md"
    local description
    description="$(extract_description "$src")"

    if $DRY_RUN; then
        echo -e "${YELLOW}[dry-run]${NC} Would create: .claude/skills/$basename/SKILL.md"
        return
    fi

    mkdir -p "$dest_dir/$basename"

    # Check if source already has frontmatter
    if head -1 "$src" | grep -q '^---$'; then
        # Already has frontmatter, copy as-is
        cp "$src" "$dest"
    else
        # Add YAML frontmatter
        {
            echo "---"
            echo "description: $description"
            echo "---"
            echo ""
            cat "$src"
        } > "$dest"
    fi
}

CORE_COUNT=0
CUSTOM_COUNT=0

# Copy core skills
if [[ -d "$CORE_SKILLS" ]]; then
    for skill in "$CORE_SKILLS"/*.md; do
        [[ -f "$skill" ]] || continue
        convert_skill "$skill" "$TARGET_SKILLS"
        CORE_COUNT=$((CORE_COUNT + 1))
    done
fi

# Copy custom skills (override core if same name)
if [[ -d "$CUSTOM_SKILLS" ]]; then
    for skill in "$CUSTOM_SKILLS"/*.md; do
        [[ -f "$skill" ]] || continue
        convert_skill "$skill" "$TARGET_SKILLS"
        CUSTOM_COUNT=$((CUSTOM_COUNT + 1))
    done
fi

echo -e "${GREEN}[OK]${NC} Skills synced: $CORE_COUNT core + $CUSTOM_COUNT custom → .claude/skills/"

# Count total skills
EXISTING_COUNT=$(find "$TARGET_SKILLS" -name 'SKILL.md' 2>/dev/null | wc -l | tr -d ' ')
echo -e "${GREEN}[OK]${NC} Total skills in .claude/skills/: $EXISTING_COUNT"

# --- Step 3: Update version.json ---
INSTANCE_NAME=$(grep -m1 'インスタンス名' "$CUSTOM_LOCAL" | awk -F'|' '{print $3}' | xargs 2>/dev/null || echo "unknown")

if ! $DRY_RUN; then
    python3 -c "
import json, datetime
v = json.load(open('$VERSION_FILE'))
v['instance_name'] = '$INSTANCE_NAME'
v['instance_id'] = '$INSTANCE_NAME'.lower().replace(' ', '-').replace('_', '-')
v['last_sync'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
json.dump(v, open('$VERSION_FILE', 'w'), indent=2, ensure_ascii=False)
print('[OK] version.json updated')
" 2>/dev/null || echo -e "${YELLOW}[WARN]${NC} Could not update version.json (python3 not available)"
fi

echo ""
echo -e "${GREEN}[sync-engine]${NC} Sync complete!"
if $DRY_RUN; then
    echo -e "${YELLOW}(dry-run mode — no files were modified)${NC}"
fi
