- generic [active] [ref=e1]:
  - banner:
    - generic:
      - link "croix":
        - /url: http://stg.croix.asia
        - img "croix"
    - generic:
      - paragraph: MENU
  - generic [ref=e3]:
    - link "EN" [ref=e4] [cursor=pointer]:
      - /url: "#"
      - generic [ref=e5]: EN
    - link "JA" [ref=e6] [cursor=pointer]:
      - /url: "#"
      - generic [ref=e7]: JA
  - main [ref=e8]:
    - heading "News 新着情報" [level=3] [ref=e13]:
      - generic [ref=e14]: News
      - generic [ref=e15]: 新着情報
    - generic [ref=e19]:
      - generic [ref=e20]:
        - generic [ref=e21]: 2025.11.28
        - generic [ref=e22]: （お知らせ）
      - heading "高校生の“音楽の使い方”からヒントを得る新しい探究型マーケティング。株式会社クロアが「StudyJam」をきっかけに、Z世代と“音と感覚”の関係を探る学びの場をスタート" [level=1] [ref=e23]
      - generic [ref=e24]:
        - paragraph [ref=e25]:
          - strong [ref=e26]: ヒーリングミュージックって知ってる？Z世代の“音の感性”に学ぶ、新しいマーケティングと教育のかたち
        - paragraph [ref=e27]:
          - text: ウェルビーイング・テクノロジー事業として数多くの癒やしのBGMを制作している株式会社クロアは、企業と高校生をつなげる探究学習型マーケティング施策「StudyJam（スタディジャム）」
          - link "https://www.ctv.co.jp/studyjam/" [ref=e28] [cursor=pointer]:
            - /url: https://www.ctv.co.jp/studyjam/
          - text: を通じて、全国の高等学校へ“音と感覚”「ヒーリングミュージック」をテーマとした新しいマーケティングを開始いたしました。
        - paragraph [ref=e29]:
          - link:
            - /url: http://stg.croix.asia/wp-content/uploads/2025/11/CROIX_StudyJam.jpg
        - paragraph [ref=e30]: 株式会社クロア × StudyJam
        - paragraph [ref=e31]:
          - strong [ref=e33]: 「StudyJam（スタディジャム）」
        - paragraph [ref=e34]: 本取り組みでは、企業のPRや商品開発における課題を「探究テーマ」として高校生に提示し、「総合的な探究の時間」や「課題研究」等の授業内で、生徒たち自身がそのテーマについて自由な発想でアイデアを探っていくことを目的としています。
        - paragraph [ref=e35]:
          - strong [ref=e37]: 探究テーマ：「音楽 × 日常のセルフケア」 ヒーリングミュージックって知ってる？
        - paragraph [ref=e38]: クロアは今回、「ヒーリングミュージック」や「音を使ったセルフケア」をテーマに、下記のような問いを高校生に投げかけ、Z世代ならではの感性や意見を集め今後のヒーリングミュージック制作における様々なアプローチを進めて参ります。
        - paragraph [ref=e39]:
          - strong [ref=e41]: ■ 高校生に伺ってみたい探究テーマ（例）
        - paragraph [ref=e42]: 音楽をどんな場面で活用していますか？（勉強、移動中、入眠前など）
        - paragraph [ref=e43]: 勉強中に音楽を聴くとき、どのタイミングで／どんな音楽を選びますか？
        - paragraph [ref=e44]:
          - text: ポップス・ロック・クラシック以外で聴く音楽はありますか？
          - text: 例：環境音、BGM、民族音楽、ヒーリング系など
        - paragraph [ref=e45]:
          - text: 「ヒーリングミュージック」という言葉を聞いたことはありますか？
          - text: → 聴くことがある場合：どんなときに／どんな気分で聴きますか？
          - text: → 聴かない／知らない場合：どうして自分には合わないと感じますか？
        - paragraph [ref=e46]: 音楽を「自分を整えるため」に使っていると感じることはありますか？
        - paragraph [ref=e47]: など
        - paragraph [ref=e48]: クロアの想い：「音楽が日常にどう関わっているか」を、高校生から学ぶ場に
        - paragraph [ref=e49]: ヒーリングミュージックや自然音といった“静かな音楽”は、近年、睡眠・集中・ストレスケアなどに効果があると言われ、音楽ストリーミングサービスやYouTube上でも多くの支持を得ています。
        - paragraph [ref=e50]: クロアでは「CROIX HEALING（クロアヒーリング）」という専門レーベルを通じて、医学博士監修の機能性音源や高精細な自然映像コンテンツなどを国内外に展開しており、今回の取り組みを通じて、次世代の視点から音と感覚の関係性を見つめ直すヒントを得たいと考えています。
        - paragraph [ref=e51]:
          - strong [ref=e53]: ヒーリング音楽マーケットでトップクラスのシェアを誇る眠りと癒やしの専門レーベル
        - paragraph [ref=e54]:
          - link:
            - /url: http://stg.croix.asia/wp-content/uploads/2025/11/CROIX-HEALING-logo.png
        - paragraph [ref=e55]:
          - text: CROIX HEALING レーベル
          - link "https://www.croixhealing.com" [ref=e56] [cursor=pointer]:
            - /url: https://www.croixhealing.com
        - paragraph [ref=e57]: 癒やしの映像と音楽がもたらす、新しいウェルビーイング体験（高精細映像コンテンツ）
        - paragraph [ref=e58]:
          - link:
            - /url: http://stg.croix.asia/wp-content/uploads/2025/11/66cadacb82f4d1cf6d0a4f706b926445.jpeg
        - paragraph [ref=e59]:
          - text: 4K Overview
          - text: RELAX WORLDⓇ Wellbeing Brand by CROIX
          - text: YouTube Ch.
          - img "▶" [ref=e60]
          - link "youtube.com/@RELAX_WORLD" [ref=e61] [cursor=pointer]:
            - /url: http://youtube.com/@RELAX_WORLD
        - paragraph [ref=e62]:
          - strong [ref=e64]: 高校生が“ヒーリングミュージックを広める仕掛け人”に
        - paragraph [ref=e65]: 「StudyJam（スタディジャム）」を通じて、高校生の皆さんが「ヒーリングミュージックをどうすればもっと同世代に届けられるか？」という問いに対し、自分たちの視点や感性でアイデアを導き出していく、そんな探究の場になればと考えています。
        - paragraph [ref=e66]: そして将来、心と身体の両面に癒やしを届ける音楽を、より良いカタチで社会に広げていってくれる存在として担ってくれるのでは。そんな思いも込めた取り組みです。
        - paragraph [ref=e67]:
          - strong [ref=e68]: ■株式会社エクオル
          - text: 事業拡張を目的とした攻めのスポットワークシステムを開発・提供。
          - text: 人々が持つ知見や体験の有効活用に力点を置くことで、
          - text: 単純労働が主流の既存スポットワークサービスとは異なる価値提供を目指しています。
          - text: 会社名：株式会社エクオル (三井物産子会社)
          - text: 代表者：代表取締役 & CEO 星野 尚広
          - text: 所在地：東京都港区北青山3-10-5 Spring Terrace Omotesando 2F
          - text: 設立：2023年9月14日
          - text: サービスURL：
          - link "https://www.metajob.jp/" [ref=e69] [cursor=pointer]:
            - /url: https://www.metajob.jp/
        - paragraph [ref=e70]:
          - strong [ref=e71]: ■中京テレビ放送が取り組む新規事業開発について
          - text: 中京テレビはこれまでの放送事業の枠を超え、
          - text: 新たな価値を届けるビジネスを生み出すことを目指して2018年に「ビジネス開発グループ」を立ち上げ。
          - text: 本サービス「
          - link "StudyJam（スタジャム）" [ref=e72] [cursor=pointer]:
            - /url: https://www.ctv.co.jp/studyjam/
          - text: 」をはじめとして、ドローン関連事業や食品関連の商品開発事業を展開しております。
          - text: 番組やイベント制作で培ってきた企画制作力とオンライン技術を組み合わせた、新規事業をご提案します！
        - paragraph [ref=e73]:
          - text: （お問合せ先）
          - text: 中京テレビ放送株式会社
          - text: ビジネスプロデュース局 ビジネス開発グループ
          - text: 電話：052-588-4641 受付時間：平日 10:00～17:00
    - generic [ref=e77]:
      - textbox "Search" [ref=e78]
      - button "search" [ref=e79] [cursor=pointer]:
        - img "search" [ref=e80]
    - generic [ref=e82]:
      - heading "Pickup" [level=2] [ref=e83]:
        - generic [ref=e84]: Pickup
      - generic [ref=e85]:
        - generic [ref=e86]:
          - link "Musiora ミュジオラ -coming soon-" [ref=e87] [cursor=pointer]:
            - /url: "#"
            - paragraph [ref=e88]:
              - generic [ref=e89]: Musiora
              - generic [ref=e90]: ミュジオラ -coming soon-
          - link "nemcaro ネムカロ" [ref=e91] [cursor=pointer]:
            - /url: http://stg.croix.asia/works/nemcaro/
            - paragraph [ref=e92]:
              - generic [ref=e93]: nemcaro
              - generic [ref=e94]: ネムカロ
          - link "Relaxest リラクゼスト" [ref=e95] [cursor=pointer]:
            - /url: https://relaxest.jp/?gad_source=1&gad_campaignid=23438734731&gbraid=0AAAAADKs12bOm465MtyfyC0W8klOhZdAI&gclid=CjwKCAiAj8LLBhAkEiwAJjbY7y3fvKS10ix2xA-VHQBqdNzasSJuDZemA7bSoQTruzl2KJwQHHjPFhoC4xkQAvD_BwE
            - paragraph [ref=e96]:
              - generic [ref=e97]: Relaxest
              - generic [ref=e98]: リラクゼスト
        - generic [ref=e99]:
          - link "RELAX WORLD Plus 癒しと眠りのアプリ -coming soon-" [ref=e100] [cursor=pointer]:
            - /url: "#"
            - paragraph [ref=e101]:
              - generic [ref=e102]: RELAX WORLD Plus
              - generic [ref=e103]: 癒しと眠りのアプリ -coming soon-
          - link "RELAX WORLD EC 癒やしと眠りのスペシャリティストア -coming soon-" [ref=e104] [cursor=pointer]:
            - /url: "#"
            - paragraph [ref=e105]:
              - generic [ref=e106]: RELAX WORLD EC
              - generic [ref=e107]: 癒やしと眠りのスペシャリティストア -coming soon-
    - generic [ref=e109]:
      - heading "Contact お問い合わせ" [level=2] [ref=e110]:
        - generic [ref=e111]: Contact
        - generic [ref=e112]: お問い合わせ
      - generic [ref=e113]:
        - paragraph [ref=e114]:
          - text: 株式会社クロアへのお問い合わせは下記メールフォームにご入力のうえ、送信してください。
          - text: Please fill out and submit the following mail form to contact croix Co.,Ltd.
        - generic [ref=e115]:
          - link "お問い合わせ" [ref=e116] [cursor=pointer]:
            - /url: http://stg.croix.asia/contact
            - generic [ref=e117]: お問い合わせ
          - link "資料ダウンロード" [ref=e118] [cursor=pointer]:
            - /url: ""
            - generic [ref=e119]: 資料ダウンロード
  - contentinfo [ref=e120]:
    - generic [ref=e121]:
      - generic [ref=e122]:
        - link "CROIX" [ref=e123] [cursor=pointer]:
          - /url: http://stg.croix.asia
          - img "CROIX" [ref=e124]
        - generic [ref=e125]:
          - paragraph [ref=e126]: 株式会社クロア
          - paragraph [ref=e127]: 〒153-0064 東京都目黒区下目黒3-7-2-7F
          - paragraph [ref=e128]: TEL 03-5436-1960 / FAX 03-5436-1961
          - paragraph [ref=e129]: 営業時間 10:00-18:30 （土・日・祝・弊社特別休日を除く）
      - generic [ref=e130]:
        - list [ref=e131]:
          - listitem [ref=e132]:
            - text: Services
            - list [ref=e133]:
              - listitem [ref=e134]:
                - link "App & Digital Platform" [ref=e135] [cursor=pointer]:
                  - /url: http://stg.croix.asia/service
              - listitem [ref=e136]:
                - link "Sound & Video" [ref=e137] [cursor=pointer]:
                  - /url: http://stg.croix.asia/sound
              - listitem [ref=e138]:
                - link "Product & Smart Products" [ref=e139] [cursor=pointer]:
                  - /url: http://stg.croix.asia/product
              - listitem [ref=e140]:
                - link "Wellness Station - Relaxest" [ref=e141] [cursor=pointer]:
                  - /url: http://stg.croix.asia/relaxest
          - listitem [ref=e142]:
            - link "Works" [ref=e143] [cursor=pointer]:
              - /url: http://stg.croix.asia/works
        - list [ref=e144]:
          - listitem [ref=e145]:
            - link "Media" [ref=e146] [cursor=pointer]:
              - /url: http://stg.croix.asia/media
          - listitem [ref=e147]:
            - link "News" [ref=e148] [cursor=pointer]:
              - /url: http://stg.croix.asia/news
          - listitem [ref=e149]:
            - link "Company" [ref=e150] [cursor=pointer]:
              - /url: http://stg.croix.asia/company
          - listitem [ref=e151]:
            - link "Access" [ref=e152] [cursor=pointer]:
              - /url: http://stg.croix.asia/access
          - listitem [ref=e153]:
            - link "Sitemap" [ref=e154] [cursor=pointer]:
              - /url: http://stg.croix.asia/sitemap
      - generic [ref=e155]:
        - generic [ref=e156]:
          - link "Facebook" [ref=e157] [cursor=pointer]:
            - /url: https://www.facebook.com/relaxworld.jp/
            - img "Facebook" [ref=e158]
          - link "Instagram" [ref=e159] [cursor=pointer]:
            - /url: https://www.instagram.com/croix_relaxworld/
            - img "Instagram" [ref=e160]
          - link "YouTube" [ref=e161] [cursor=pointer]:
            - /url: https://www.youtube.com/@RELAX_WORLD
            - img "YouTube" [ref=e162]
        - generic [ref=e163]:
          - link "Sitemap" [ref=e164] [cursor=pointer]:
            - /url: http://stg.croix.asia/sitemap
          - link "個人情報保護方針" [ref=e165] [cursor=pointer]:
            - /url: http://stg.croix.asia/cookie
          - link "Privacy policy" [ref=e166] [cursor=pointer]:
            - /url: http://stg.croix.asia/privacy
        - paragraph [ref=e167]: © 2025 CROIX